// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_rCondHurdle
double cpp_rCondHurdle(NumericVector x, int j, NumericMatrix G, NumericMatrix H, NumericMatrix K, double tol);
RcppExport SEXP SingleCellAnalysis_cpp_rCondHurdle(SEXP xSEXP, SEXP jSEXP, SEXP GSEXP, SEXP HSEXP, SEXP KSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type j(jSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type H(HSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP );
        Rcpp::traits::input_parameter< double >::type tol(tolSEXP );
        double __result = cpp_rCondHurdle(x, j, G, H, K, tol);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// cpp_rGibbsHurdle
NumericMatrix cpp_rGibbsHurdle(NumericMatrix G, NumericMatrix H, NumericMatrix K, int Nt, double tol);
RcppExport SEXP SingleCellAnalysis_cpp_rGibbsHurdle(SEXP GSEXP, SEXP HSEXP, SEXP KSEXP, SEXP NtSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type H(HSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type K(KSEXP );
        Rcpp::traits::input_parameter< int >::type Nt(NtSEXP );
        Rcpp::traits::input_parameter< double >::type tol(tolSEXP );
        NumericMatrix __result = cpp_rGibbsHurdle(G, H, K, Nt, tol);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
