# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rCondHurdle <- function(x, j, G, H, K, tol) {
    .Call('SingleCellAnalysis_cpp_rCondHurdle', PACKAGE = 'SingleCellAnalysis', x, j, G, H, K, tol)
}

#' @export
.rGibbsHurdle <- function(G, H, K, Nt, tol) {
    .Call('SingleCellAnalysis_cpp_rGibbsHurdle', PACKAGE = 'SingleCellAnalysis', G, H, K, Nt, tol)
}

